name: Backend CI



on:

  push:

    paths:

      - 'backend/**'

  pull_request:

    paths:

      - 'backend/**'



jobs:

  build:

    runs-on: ubuntu-latest



    steps:

      - name: Checkout code

        uses: actions/checkout@v3



      - name: Set up Java

        uses: actions/setup-java@v3

        with:

          java-version: '17'

          distribution: 'temurin'



      - name: Build backend with Maven

        run: mvn -f backend/pom.xml clean install