name: Backend CI



on:

  push:

    paths:

      - 'backend/**'

  pull_request:

    paths:

      - 'backend/**'



jobs:

  build:

    runs-on: ubuntu-latest



    steps:

      - name: Checkout du code

        uses: actions/checkout@v3



      - name: Setup Java

        uses: actions/setup-java@v3

        with:

          java-version: '17'

          distribution: 'temurin'



      - name: Build avec Maven

        run: |

          cd backend

          ./mvnw clean install